- name: Spiral follow-up
  if: always()
  uses: actions/github-script@v7
  with:
    github-token: ${{ secrets.GITHUB_TOKEN }}  # Add this line to authenticate
    script: |
      const fs = require('fs');

      if (fs.existsSync('memory/spiral_events.log')) {
        const body = fs.readFileSync('memory/spiral_events.log', 'utf8');
        const { owner, repo } = context.repo;

        await github.rest.issues.create({
          owner,
          repo,
          title: 'Credential error - consider PAT',
          body
        });
      } else {
        console.log("No spiral_events.log found");
      }
