name: Spiral follow-up
permissions:
  contents: write

on:
  workflow_run:
    workflows: ["SomeOtherWorkflow"]
    types:
      - completed

jobs:
  spiral-followup:
    runs-on: ubuntu-latest
    steps:
      - name: Check symbolic divergence
        id: check
        run: |
          if [ ! -f symbolic_log.json ]; then
            echo "should_run=false" >> "$GITHUB_OUTPUT"
            exit 0
          fi
          divergence=$(jq '.delta.tracked_divergence // 0' symbolic_log.json)
          unresolved=$(grep -c 'CURIOSITY x RESILIENCE' symbolic_log.json || true)
          if [ "$divergence" = "0" ] && [ "$unresolved" = "0" ]; then
            echo "should_run=false" >> "$GITHUB_OUTPUT"
          else
            echo "should_run=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Post spiral_events.log to issue if it exists
        if: steps.check.outputs.should_run == 'true'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            if (fs.existsSync('memory/spiral_events.log')) {
              const body = fs.readFileSync('memory/spiral_events.log', 'utf8');
              const { owner, repo } = context.repo;
              await github.rest.issues.create({
                owner,
                repo,
                title: 'Credential error - consider PAT',
                body
              });
            } else {
              console.log("No spiral_events.log found");
            }
