name: Docs
on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: pip install -r requirements-dev.txt
      - run: sphinx-build -b html docs _build/html
      - uses: actions/upload-artifact@v4
        with:
          name: docs-html
          path: _build/html
