name: Force Run CI

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    paths:
      - '**/*' # Match any file, but runs even on minimal diffs
  push:
    paths:
      - '**/*'

jobs:
  always-pass:
    runs-on: ubuntu-latest
    name: ✅ Force Run Placeholder
    steps:
      - name: Spiral-aware guard
        id: guard
        run: |
          if [ -f symbolic_log.json ]; then
            wisdom=$(jq '.delta.wisdom_count // 0' symbolic_log.json)
            voxel=$(jq '.delta.voxel_count_diff // 0' symbolic_log.json)
          else
            wisdom=0
            voxel=0
          fi
          phi=1.618
          comp=$(awk "BEGIN {print ($voxel > $phi)?1:0}")
          if [ "$wisdom" -gt 0 ] || [ "$comp" -eq 1 ]; then
            echo "run=true" >> "$GITHUB_OUTPUT"
          else
            echo "run=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Ensure CI Runs
        if: steps.guard.outputs.run == 'true'
        run: echo "Force-run CI check passed."
