name: Force Run CI

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    paths:
      - '**/*' # Match any file, but runs even on minimal diffs
  push:
    paths:
      - '**/*'

jobs:
  always-pass:
    runs-on: ubuntu-latest
    name: ✅ Force Run Placeholder
    steps:
      - name: Ensure CI Runs
        run: echo "Force-run CI check passed."
