name: Publish Python Package

on:
  push:
    branches: ['**']
    tags:
      - 'v*.*.*'
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Auto-increment patch version in pyproject.toml
        run: |
          path="pyproject.toml"
          python - <<EOF
import re
with open("$path") as f:
    s = f.read()
new = re.sub(
    r'version\s*=\s*"(\\d+)\\.(\\d+)\\.(\\d+)"',
    lambda m: f'version = "{m.group(1)}.{m.group(2)}.{int(m.group(3))+1}"',
    s
)
with open("$path", "w") as f:
    f.write(new)
EOF

      - name: Build package
        run: |
          pip install build
          python -m build

      - name: Publish to GitHub Packages
        run: |
          pip install twine
          twine upload --repository-url https://upload.pypi.org/legacy/ dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
