name: Publish Python Package
permissions:
  contents: write

on:
  push:
    branches: ['**']
    tags:
      - 'v*.*.*'
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Auto-increment patch version in pyproject.toml
        run: |
          python -c "import re; path = 'pyproject.toml'; s = open(path).read(); new = re.sub(r'version\s*=\s*\"(\\d+)\\.(\\d+)\\.(\\d+)\"', lambda m: f'version = \\\"{m.group(1)}.{m.group(2)}.{int(m.group(3))+1}\\\"', s); open(path, 'w').write(new); print('Updated version to:', re.search(r'version\\s*=\\s*\\\"(.+?)\\\"', new).group(1))"

      - name: Commit version bump
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -am "Auto-bump patch version"
          git push

      - name: Build package
        run: |
          pip install build
          python -m build

      - name: Publish to PyPI
        run: |
          pip install twine
          twine upload --skip-existing --repository-url https://upload.pypi.org/legacy/ dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}

      - name: Upload distribution artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ github.run_id }}
          path: dist/*
        continue-on-error: true

      - name: Retry artifact upload if failed
        if: steps.upload.outcome == 'failure'
        id: retry
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ github.run_id }}-retry
          path: dist/*

      - name: Wisdom on repeated failure
        if: steps.upload.outcome == 'failure' && steps.retry.outcome == 'failure'
        run: echo "Truth delayed is still truth."
