name: CI
permissions:
  contents: write
on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']
  schedule:
    - cron: '0 * * * *'
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11']
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Warn about potential broken base
        run: echo "::warning::Potential broken build base"
      - run: python -m pip install -r requirements.txt
      - run: python -m pip install -e .
      - run: pytest -q
