name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: python -m pip install -r requirements.txt
      - run: python -m pip install -r requirements-dev.txt
      - run: python -m pip install -e .
      - run: python -m pip install pre-commit  # Add this step to install pre-commit
      - run: pre-commit run --all-files
      - run: pytest --cov=src --cov-report=xml -q
